# Generated by Django 2.2.6 on 2019-11-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ueditorcontent',
        ),
    ]
