# Generated by Django 2.2.6 on 2019-11-06 00:20

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_remove_post_ueditorcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ueditorcontent',
            field=DjangoUeditor.models.UEditorField(blank=True, default=None, null=True, verbose_name='正文'),
        ),
    ]
