# Generated by Django 2.1.7 on 2019-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compression_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip地址')),
                ('filename', models.CharField(blank=True, max_length=100, null=True, verbose_name='源文件名')),
                ('before_size', models.FloatField(blank=True, max_length=10, null=True, verbose_name='压缩前大小')),
                ('after_size', models.FloatField(blank=True, max_length=10, null=True, verbose_name='压缩后大小')),
                ('compression_ratio', models.FloatField(blank=True, max_length=10, null=True, verbose_name='压缩比')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '压缩日志',
                'verbose_name_plural': '压缩日志',
            },
        ),
    ]
