# Generated by Django 2.1.7 on 2019-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf2zip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compression_log',
            name='state',
            field=models.IntegerField(choices=[(0, '请上传待压缩的PDF文件'), (1, '上传成功，待压缩'), (2, '压缩成功，待下载'), (3, '下载成功，完成！')], default=0, verbose_name='状态'),
        ),
    ]
