# Generated by Django 2.2.2 on 2019-08-12 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='问题')),
                ('content', models.CharField(max_length=1000, verbose_name='详细描述')),
                ('datetime', models.TimeField(auto_now_add=True, verbose_name='时间')),
                ('status', models.PositiveIntegerField(choices=[(0, '正常'), (1, '关闭')], default=0, verbose_name='状态')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提问者')),
            ],
            options={
                'verbose_name': '问题清单',
                'verbose_name_plural': '问题清单',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='回答')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('ip_address', models.CharField(max_length=10, verbose_name='IP地址')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='响应者')),
            ],
            options={
                'verbose_name': '回答列表',
                'verbose_name_plural': '回答列表',
            },
        ),
    ]
