# Generated by Django 2.2.2 on 2019-08-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
