# Generated by Django 2.2.2 on 2019-08-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20190816_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='questions',
            name='thumbs_up',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
    ]
