# Generated by Django 2.2.2 on 2019-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20190818_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(verbose_name='详细描述'),
        ),
    ]
