# Generated by Django 2.2.2 on 2019-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(verbose_name='回答'),
        ),
    ]
