# Generated by Django 2.2.2 on 2019-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default='', help_text='正文必须为MarkDown格式', verbose_name='正文HTML代码'),
        ),
    ]
