# Generated by Django 2.1.7 on 2019-03-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='sidebar',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
